mysql:
  path: 127.0.0.1
  port: 3306
  dbname: university_selection
  config: charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password:
  max-idle-conns: 0
  max-open-conns: 0
  logmode:
  logzap: true