# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    branches: [ "main" ] # master 分支提交时触发
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go #配置GO 环境
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build # 编译项目
      run: go build -v ./...

    - name: 发布到阿里云
      uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到阿里云
      with:
          username: 'root'
          server: '${{ secrets.ALIYUN_SERVER_HOST }}'
          ssh_private_key: '${{ secrets.ALIYUN_SERVER_PRIVATE_KEY }}'
          local_path: './*'
          remote_path: '/root/university-selection_Backend/'
          args: "-o ConnectTimeout=5"
